

spring:
  datasource:
    users:
      url: jdbc:postgresql://localhost:6000/studs
      username: s313083
      password: qZTAZnu9jQZoIVVj
      driver-class-name: org.postgresql.Driver
    articles:
      url: jdbc:postgresql://localhost:5431/blps
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings

app:
  jwtSecret: 77BB8D1285FF9F029850511B3ECC8B0EA3DFFB0987762701471144681C07F4E4

logging:
  level:
    org:
      springframework:
        security: DEBUG


